### ISSUE TITLE
BICB & v flag

### ISSUE THREAD

**Issue by folkertvanheusden** [outofmbufs/python-pdp11-emulator#1]
Hi,

Shouldn't BIC(B) clear the V-flag?

**Comment by outofmbufs** [comment]
ooops. Yes. Thank you!

**Comment by folkertvanheusden** [comment]
The patch can be found here https://github.com/outofmbufs/python-pdp11-emulator/pull/2

Thanks for writing this emulator! I use it to generate validation-data for my own emulator.

**Comment by outofmbufs** [comment]
Cool - glad someone is finding it useful/helpful!
