### ISSUE TITLE
addressing modes

### ISSUE THREAD

**Issue by folkertvanheusden** [outofmbufs/python-pdp11-emulator#4]
Hi,

I'm not 100% sure but regarding https://github.com/outofmbufs/python-pdp11-emulator/blob/main/machine.py#L454
At line 463 for registers that are not SP/PC, the autoincrement is set to word_size. But I think that should always be 2 unless I mis-interpret https://bitsavers.org/pdf/dec/pdp11/1170/PDP-11_70_Handbook_1977-78.pdf page 33, 3-9.
"Register is first used as a pointer to a word containing the address of the operand, then incremented (always by 2; even for byte instructions)". Same for mode 5 (which currently only for SP decrements by 2).

**Comment by outofmbufs** [comment]
You are, of course, correct, as verified by common sense, the book, and SIMH. Kind of a miracle I got this far with that bug in there. Working on fixing it (with corresponding tests).

SIMH confirmation:
PDP-11 simulator Open SIMH V4.1-0 Current        git commit id: 4e159a04
sim> d 10000 12700
sim> d 10002 20000
sim> d 10004 12737
sim> d 10006 30000
sim> d 10010 20000
sim> d 10012 112730
sim> d 10014 42
sim> e -m 10000-10020
10000:	MOV #20000,R0
10004:	MOV #30000,@#20000
10012:	MOVB #42,@(R0)+
10016:	HALT
10020:	HALT
sim> d pc 10000
sim> run

HALT instruction, PC: 010020 (HALT)
sim> e r0
R0:	020002

**Comment by outofmbufs** [comment]
Fixed; see machine.py, and tests in pdptests.py
