### ISSUE TITLE
python  & signmask

### ISSUE THREAD

**Issue by folkertvanheusden** [outofmbufs/python-pdp11-emulator#6]
In RORB (and others):

```
     cpu.psw_n = val & signmask
    cpu.psw_z = (val == 0)
     cpu.psw_v = cpu.psw_n ^ cpu.psw_c
```

Now val is 0...255. Signmask is 128. So psw_n can be 128 and 0.
This makes psw_v into 0, 1, 128 or 129.

_brconds (in branches.py) for v-flag is:
```
    0o102000: lambda n, z, v, c: not v,            # BVC
    0o102400: lambda n, z, v, c: v,                # BVS
```

I think you shold either make the lambda in: "not (v & 1)" and "(v & 1)" or the asignment of the n-flag into e.g.:
```     cpu.psw_n = 1 if  val & signmask else 0```

**Comment by folkertvanheusden** [comment]
```
op000.py:    cpu.psw_n = val & cpu.SIGN8
op00.py:    cpu.psw_n = val & cpu.SIGN816[opsize]
op00.py:    cpu.psw_n = newval & cpu.SIGN816[opsize]
op00.py:    cpu.psw_n = newval & cpu.SIGN816[opsize]
op00.py:    cpu.psw_n = newval & cpu.SIGN816[opsize]
op00.py:    cpu.psw_n = (val & cpu.SIGN816[opsize])
op00.py:    cpu.psw_n = (val & cpu.SIGN816[opsize])
op00.py:    cpu.psw_n = (val & cpu.SIGN816[opsize])
op00.py:    cpu.psw_c, val = (val & signmask), ((val << 1) | vc) & cpu.MASK816[opsize]
op00.py:    cpu.psw_c = (val & cpu.SIGN816[opsize])
op00.py:    cpu.psw_n = pival & cpu.MASK16
op00.py:    cpu.psw_n = w & cpu.MASK16
op07.py:    cpu.psw_n = m & 0x80000000
op07.py:    cpu.psw_n = (value & signmask)
op07.py:    cpu.psw_n = (r & cpu.SIGN16)
op4.py:    cpu.psw_n = (val & 0o200)
op4.py:    cpu.psw_n = (t & signbit)
op4.py:    cpu.psw_n = t & cpu.SIGN816[opsize]
op4.py:    cpu.psw_n = dst & cpu.SIGN816[opsize]
op4.py:    cpu.psw_n = dst & cpu.SIGN816[opsize]
op4.py:    cpu.psw_n = (t & cpu.SIGN16)
op4.py:    cpu.psw_n = (t & cpu.SIGN16)
```

**Comment by folkertvanheusden** [comment]
If you agree, then https://github.com/outofmbufs/python-pdp11-emulator/pull/7 is a patch for that (hopefully I found every case).

**Comment by outofmbufs** [comment]
Ugh .. I got this right in branches but not here. I think the better fix is to replace the four instances of

    cpu.psw_v = cpu.psw_n ^ cpu.psw_c

in op00.py with

    cpu.psw_v = bool(cpu.psw_n) != bool(cpu.psw_c)

I searched for other uses of '^' ... this should be the only ones.

Might not get around to testing / checking in this change until later today / this weekend (I want to write test cases too).

**Comment by folkertvanheusden** [comment]
Please consider adding RK05 or RL02 support so that one can run the XXDP
diagnostics set. Maybe that finds other issues (if any!).


regards

**Comment by outofmbufs** [comment]
Fixed this bug w/changes (only) in op00.py (use bool(A) != bool(B) instead of A^B)
