### ISSUE TITLE
SOB?

### ISSUE THREAD

**Issue by folkertvanheusden** [outofmbufs/python-pdp11-emulator#9]
Hi,

Are you sure about the current SOB implementation?
It is subtle different from other implementations I saw (p11, simh) and behaves a tiny bit different because of that.

I think it should be:
```
def op077_sob(cpu, inst):
    srcreg = (inst & 0o000700) >> 6
    r = (cpu.r[srcreg] - 1) & 0xffff

    if r != 0:
        # technically if this instruction occurs low enough in memory
        # this PC subtraction could wrap, so be technically correct & mask
        cpu.r[cpu.PC] = (cpu.r[cpu.PC] - 2 * (inst & 0o077)) & cpu.MASK16

    cpu.r[srcreg] = r
```

See https://github.com/open-simh/simh/blob/master/PDP11/pdp11_cpu.c#L1895

https://github.com/outofmbufs/python-pdp11-emulator/pull/8

**Comment by outofmbufs** [comment]
Well, I'm not entirely sure why I wrote that code that way, it's certainly less-clear than it could be, but I think the two implementations are identical. Here's a test showing that -- unless you think I've overlooked something.

For the test code, I replaced "cpu.r[srcreg]" with just a function argument (see the code below) and have the functions return a tuple: True/False (branch taken or not) and the modified register value. They produce identical results for all inputs 0 .. 65535:

Put this in a file foo.py and "python3 foo.py" to run it.

def sobSIMH(srcreg):
    
    r = (srcreg - 1) & 0xffff
    if r != 0:
        return r, True              # branch
    return r, False                 # no branch

def sobNW(srcreg):
    r = srcreg

    if r == 1:
        r = 0
    else:
        if r > 0:
            r -= 1
        else:
            r = 0o177777    # 0 means max, that's how SOB is defined

        return r, True

    return r, False

if __name__ == "__main__":
    import unittest

    class TestMethods(unittest.TestCase):
        def test_compare(self):
            for srcreg in range(65536):
                self.assertEqual(sobNW(srcreg), sobSIMH(srcreg))

    unittest.main()

**Comment by outofmbufs** [comment]
ugh - code got hosed in cut/paste. Get it here for now:
https://www.dropbox.com/scl/fi/mfxyo2gqsv1e4fe5m2an8/sobx.py?rlkey=o41hjnaf389kdp1la5nng6rnh&dl=0

**Comment by folkertvanheusden** [comment]
Hmmm you're absolutely right indeed.
Sorry for the confusion, could've verified that myself!

Have you tried to compile the python code by the way? I tried shedskin and
nuitka3 but both failed unfortunately.

**Comment by outofmbufs** [comment]
Took the pull even though old code worked. New code is simpler.

Never tried compiling. I did spend a little time trying to make the simplest instructions (register-to-register moves in particular) go fast, but at some point if performance is that important "use SIMH" becomes a better answer. I was just happy that it booted v7 (despite all the recently-found bugs! lol) and ran at a reasonable speed.
